[workspace]
members = [
    "client",
    "coordinator",
    "endorser",
    "ledger",
    "store",
    "verifier",
    "bench",
    "endpoint",
    "endpoint_grpc",
    "light_client",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
