[workspace]
members = [
    "client",
    "coordinator",
    "endorser",
    "ledger",
    "verifier",
    "bench",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
