name: Build Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
      HASH_ID: ${GITHUB_SHA::8}
      PUSH_IMAGE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build the Docker images
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger:${{ env.HASH_ID }}
          docker build --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-benchmark:${{ env.HASH_ID }} --target benchmark .
          docker build --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-client:${{ env.HASH_ID }} --target client .
          docker build --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-coordinator:${{ env.HASH_ID }} --target coordinator .
          docker build --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-endorser:${{ env.HASH_ID }} --target endorser .
      - name: Push the Docker images to Container Registry
        if: env.PUSH_IMAGE == 'true'
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger:${{ env.HASH_ID }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-benchmark:${{ env.HASH_ID }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-client:${{ env.HASH_ID }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-coordinator:${{ env.HASH_ID }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nimbleledger-endorser:${{ env.HASH_ID }}
